### ISSUE TITLE
Create requirements for valid username/password

### ISSUE THREAD

**Issue by sali45** [gt-8133/inventory-manager#14]
Acceptance Criteria: Industry standards for a good password are created. 

Make the password 8 characters or longer

Use at least one lowercase letter (a - z), one uppercase letter (A - Z), one special character(i.e. 
'?', '!'), and one numeral (0 - 9).

**Comment by Bkucera** [comment]
Check out code in `server/src/` for the current validation for email and password.

**Comment by chadgerhard** [comment]
We're not setting requirements because we're using GT credentials through CAS
