### ISSUE TITLE
Error with postinstall script when running npm install

### ISSUE THREAD

**Issue by sali45** [gt-8133/inventory-manager#48]
Here's the error log after running `npm install`. 
`
Did you mean one of these?
    c
    i
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! inventory-manager@ postinstall: `cd server; npm ci`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the inventory-manager@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by Bkucera** [comment]
Make sure you're using the most recent version of npm, 
```
npm i -g npm
```
